### ISSUE TITLE
15. Merchant Invoice Show Page

### ISSUE THREAD

**Issue by kbug819** [Antoine-Aube/little-shop-7#36]
As a merchant
When I visit my merchant's invoice show page (/merchants/:merchant_id/invoices/:invoice_id)
Then I see information related to that invoice including:
- Invoice id
- Invoice status
- Invoice created_at date in the format "Monday, July 18, 2019"
- Customer first and last name

**Comment by Antoine-Aube** [comment]
merged 9/11 #62

**Comment by williamfchen** [comment]
my view is displaying duplicate information.  Need to debug

**Comment by Antoine-Aube** [comment]
It's not duplicate on my end? Not sure what you're seeing. We can chat a bit later.
